# Generated for the shared bonus platform.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIProviderConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("openai", "OpenAI"), ("google", "Google Gemini"), ("anthropic", "Anthropic")], max_length=30)),
                ("model", models.CharField(max_length=120)),
                ("api_key", models.CharField(blank=True, default="", max_length=500)),
                ("enabled", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=100)),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["priority", "provider"]},
        ),
        migrations.CreateModel(
            name="Casino",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.CharField(blank=True, default="", max_length=180)),
                ("type", models.CharField(blank=True, default="", max_length=80)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("aggregator_type", models.CharField(blank=True, default="", max_length=120)),
                ("aggregator_source", models.CharField(blank=True, default="", max_length=255)),
                ("regulated_option", models.CharField(blank=True, default="", max_length=80)),
                ("crypto_friendly_option", models.CharField(blank=True, default="", max_length=80)),
                ("my_brand", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="bonus_core_casino_name_idx"),
                    models.Index(fields=["priority"], name="bonus_core_casino_priority_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GameProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("logo_url", models.URLField(blank=True, default="")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Geo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("is_regulated", models.BooleanField(default=False)),
                ("sort", models.IntegerField(default=0)),
                ("has_ppc", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="bonus_core.geo")),
            ],
            options={"ordering": ["sort", "name"]},
        ),
        migrations.CreateModel(
            name="Vertical",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("geo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="telegram_users", to="bonus_core.geo")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="casino",
            name="verticals",
            field=models.ManyToManyField(blank=True, related_name="casinos", to="bonus_core.vertical"),
        ),
        migrations.CreateModel(
            name="AffiliateAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password", models.CharField(blank=True, default="", max_length=255)),
                ("affiliate_id", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("casino", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="affiliate_account", to="bonus_core.casino")),
            ],
        ),
        migrations.CreateModel(
            name="AffiliateMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=1000)),
                ("affiliate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="bonus_core.affiliateaccount")),
                ("geo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="affiliate_media", to="bonus_core.geo")),
            ],
            options={"verbose_name_plural": "Affiliate media"},
        ),
        migrations.CreateModel(
            name="CasinoBonusPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_code", models.CharField(blank=True, default="", max_length=32)),
                ("url", models.URLField(max_length=1000)),
                ("notes", models.TextField(blank=True, default="")),
                ("affiliate_url", models.URLField(blank=True, default="", max_length=1000)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("casino", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bonus_pages", to="bonus_core.casino")),
                ("geo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bonus_pages", to="bonus_core.geo")),
            ],
            options={
                "ordering": ["-priority", "casino__name", "geo__sort", "url"],
                "indexes": [
                    models.Index(fields=["source_code"], name="bc_bpage_source_idx"),
                    models.Index(fields=["is_active"], name="bc_bpage_active_idx"),
                    models.Index(fields=["priority"], name="bc_bpage_priority_idx"),
                ],
                "unique_together": {("casino", "geo", "source_code", "url")},
            },
        ),
        migrations.CreateModel(
            name="CasinoLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_traffic_share", models.IntegerField(default=0)),
                ("location_id", models.IntegerField(blank=True, null=True)),
                ("total_share_of_traffic", models.IntegerField(default=0)),
                ("market_share", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("websites_found", models.IntegerField(default=0)),
                ("casino", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="bonus_core.casino")),
                ("geo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="casino_locations", to="bonus_core.geo")),
            ],
            options={"ordering": ["geo__sort", "position"], "unique_together": {("casino", "geo")}},
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("type", models.CharField(blank=True, default="", max_length=120)),
                ("rtp", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="games", to="bonus_core.gameprovider")),
            ],
            options={"ordering": ["name"], "unique_together": {("provider", "name")}},
        ),
        migrations.CreateModel(
            name="ScrapedHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=1000)),
                ("scraped_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("SUCCESS", "Success"), ("FAILED", "Failed"), ("SKIPPED", "Skipped")], max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
                ("raw_html", models.TextField(blank=True, default="")),
                ("final_url", models.URLField(blank=True, default="", max_length=1000)),
                ("aggregator_type", models.CharField(blank=True, default="", max_length=120)),
                ("bonus_page", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scrape_history", to="bonus_core.casinobonuspage")),
                ("casino", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scrape_history", to="bonus_core.casino")),
                ("geo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scrape_history", to="bonus_core.geo")),
            ],
            options={
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(fields=["status", "scraped_at"], name="bonus_core_scraped_status_idx"),
                    models.Index(fields=["url"], name="bonus_core_scraped_url_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIParsingQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scraped_history_id_external", models.IntegerField(blank=True, null=True)),
                ("url", models.URLField(max_length=1000)),
                ("raw_html", models.TextField()),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("PROCESSING", "Processing"), ("DONE", "Done"), ("FAILED", "Failed")], default="PENDING", max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
                ("traceback", models.TextField(blank=True, default="")),
                ("casino", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_queue_items", to="bonus_core.casino")),
                ("geo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_queue_items", to="bonus_core.geo")),
                ("scraped_history", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_queue_items", to="bonus_core.scrapedhistory")),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["status", "created_at"], name="bonus_core_aiparse_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="Bonus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("type", models.CharField(blank=True, default="", max_length=120)),
                ("wagering_requirement", models.CharField(blank=True, default="", max_length=255)),
                ("min_deposit", models.CharField(blank=True, default="", max_length=120)),
                ("max_bonus", models.CharField(blank=True, default="", max_length=120)),
                ("currency", models.CharField(blank=True, default="", max_length=30)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("bonus_url", models.URLField(blank=True, default="", max_length=1000)),
                ("is_auto", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("casino", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bonuses", to="bonus_core.casino")),
                ("game", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bonuses", to="bonus_core.game")),
                ("geo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bonuses", to="bonus_core.geo")),
                ("provider", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bonuses", to="bonus_core.gameprovider")),
                ("source_scraped_history", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bonuses", to="bonus_core.scrapedhistory")),
            ],
            options={
                "ordering": ["-priority", "-casino__priority", "-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "is_approved"], name="bonus_core_bonus_state_idx"),
                    models.Index(fields=["priority", "created_at"], name="bonus_core_bonus_rank_idx"),
                    models.Index(fields=["type"], name="bonus_core_bonus_type_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notify_enabled", models.BooleanField(default=True)),
                ("preferred_currency", models.CharField(blank=True, max_length=30, null=True)),
                ("preferred_language", models.CharField(default="en", max_length=16)),
                ("receive_crypto_bonuses", models.BooleanField(default=True)),
                ("receive_freespins", models.BooleanField(default=True)),
                ("receive_deposit_bonuses", models.BooleanField(default=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="settings", to="bonus_core.telegramuser")),
            ],
            options={"verbose_name_plural": "User settings"},
        ),
        migrations.CreateModel(
            name="UserCasinoSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("casino", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="telegram_subscribers", to="bonus_core.casino")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="casino_subscriptions", to="bonus_core.telegramuser")),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("user", "casino")}},
        ),
        migrations.CreateModel(
            name="NotificationHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bonus_reference_id", models.IntegerField()),
                ("sent_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("SENT", "Sent"), ("FAILED", "Failed")], max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("bonus", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notification_history", to="bonus_core.bonus")),
                ("casino", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notification_history", to="bonus_core.casino")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_history", to="bonus_core.telegramuser")),
            ],
            options={"ordering": ["-sent_at"], "verbose_name_plural": "Notification history", "unique_together": {("user", "bonus_reference_id")}},
        ),
    ]
